### ISSUE TITLE
Demo link yada video

### ISSUE THREAD

**Issue by osmansoylemez** [Rumeysakeskin/text2speech#4]
Selamlar, geliştirilen TTS yapısının web üzerinden kullanılabilecek demo linki mevcut mu? Video da olabilir. Türkçe telaffuzda nasıl bir başarı elde ettiğinizi çok merak ediyorum.

**Comment by atesahmet0** [comment]
Böyle bir paylaşım harika olur

**Comment by Rumeysakeskin** [comment]
> Selamlar, geliştirilen TTS yapısının web üzerinden kullanılabilecek demo linki mevcut mu? Video da olabilir. Türkçe telaffuzda nasıl bir başarı elde ettiğinizi çok merak ediyorum.

Merhaba @osmansoylemez, @atesahmet0 
Bu repodaki TTS modeli beklentileri tam olarak karşılamadı, ancak geliştirmelere farklı TTS modelleri ile devam ediyorum.
Türkçe TTS için [mms-tts](https://github.com/Rumeysakeskin/mms-turkish-tts) 'i incelemenizi öneririm. 
Facebook's [Massively Multilingual Speech](https://arxiv.org/abs/2305.13516) projesi farklı dillerdeki TTSlerin kullanılmasına olanak tanıyor.
